CREATE OR REPLACE TABLE `user` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `username` varchar(250) NOT NULL,
    `password` varchar(250) NOT NULL,
    `firstName` VARCHAR(100) NOT NULL,
    `surname` VARCHAR(100) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

INSERT INTO user (username, password, surname, firstName) VALUES
    ('admin', '$2y$10$P6.Hp/NcWeLWuV53NsV9X.BLbJQ2w1IxVulDJ2pI8cKCi.OgErNz.', 'User', 'Administrator');

CREATE OR REPLACE TABLE `securityToken` (
    `id` bigint unsigned AUTO_INCREMENT,
    `userId` bigint unsigned NOT NULL,
    `identifier` varchar(256) NOT NULL,
    `token` varchar(256) NOT NULL,
    `created` timestamp NULL DEFAULT NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`userId`) REFERENCES `user` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE OR REPLACE TABLE `trainingCourse` (
    `id` bigint unsigned AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE TABLE OR REPLACE `interested` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `gender` char(1) NOT NULL,
  `firstName` varchar(200) NOT NULL,
  `surname` varchar(200) NOT NULL,
  `birthDate` date DEFAULT NULL,
  `birthLocation` varchar(200) DEFAULT NULL,
  `maritalStatus` varchar(100) DEFAULT NULL,
  `hasChilds` tinyint(1) NOT NULL DEFAULT 0,
  `street` varchar(500) DEFAULT NULL,
  `postCode` char(5) DEFAULT NULL,
  `location` varchar(500) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `phonePrivate` varchar(100) DEFAULT NULL,
  `phoneMobile` varchar(100) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `legalRepresentative` varchar(400) DEFAULT NULL,
  `emailLegalRepresentative` varchar(200) DEFAULT NULL,
  `phoneLegalRepresentative` varchar(100) DEFAULT NULL,
  `lastGraduation` varchar(200) DEFAULT NULL,
  `graduationYear` int(11) DEFAULT NULL,
  `lastSchool` varchar(200) DEFAULT NULL,
  `schoolFrom` date DEFAULT NULL,
  `schoolTo` date DEFAULT NULL,
  `hasBoardingSchoolExperience` tinyint(1) NOT NULL DEFAULT 0,
  `germanLevel` varchar(2) NOT NULL,
  `degreeOfVisualImpairment` char(1) DEFAULT NULL,
  `otherDisability` char(1) DEFAULT NULL,
  `requiredAccessibilityTools` longtext DEFAULT NULL,
  `handicappedIdAvailable` tinyint(1) NOT NULL DEFAULT 0,
  `medicalRemarks` longtext DEFAULT NULL,
  `pensionInsuranceNumber` char(12) DEFAULT NULL,
  `taxID` char(11) DEFAULT NULL,
  `taxClass` char(2) DEFAULT NULL,
  `denomination` varchar(50) DEFAULT NULL,
  `healthInsuranceName` varchar(200) DEFAULT NULL,
  `healthInsuranceNumber` varchar(30) DEFAULT NULL,
  `membershipCertificateForHealthInsuranceAvailable` tinyint(1) NOT NULL DEFAULT 0,
  `paymentOfSVContributions` varchar(50) DEFAULT NULL,
  `retraining` tinyint(1) NOT NULL DEFAULT 0,
  `trainingCourse1Id` bigint(20) UNSIGNED DEFAULT NULL,
  `trainingCourse2Id` bigint(20) UNSIGNED DEFAULT NULL,
  `electives` longtext DEFAULT NULL,
  `orientationWeekInterest` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekFrom` date DEFAULT NULL,
  `orientationWeekTo` date DEFAULT NULL,
  `orientationWeekAccommodationRequired` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekCostCommitmentRequested` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekPayer` varchar(200) DEFAULT NULL,
  `orientationWeekRemarks` longtext DEFAULT NULL,
  `orientationWeekCostCommitmentReceived` tinyint(1) NOT NULL DEFAULT 0,
  `trainingFrom` date DEFAULT NULL,
  `trainingTo` date DEFAULT NULL,
  `payerName` varchar(200) DEFAULT NULL,
  `payerAddress` varchar(500) DEFAULT NULL,
  `payerContactPerson` varchar(200) DEFAULT NULL,
  `payerPhone` varchar(100) DEFAULT NULL,
  `payerCustomerNumber` varchar(100) DEFAULT NULL,
  `payerCostCommitment` varchar(20) DEFAULT NULL,
  `payerRemarks` longtext DEFAULT NULL,
  `accommodation` varchar(20) DEFAULT NULL,
  `youthProtectionExaminationReceived` tinyint(1) NOT NULL DEFAULT 0,
  `created` timestamp NOT NULL DEFAULT current_timestamp(),
  `trainingContract` varchar(20) DEFAULT NULL,
  `lpf` longtext DEFAULT NULL,
  `oAndM` longtext DEFAULT NULL,
  `trainingStartRemarks` longtext DEFAULT NULL,
  `remarksInt` longtext DEFAULT NULL,
  `sourceOfFirstContact` longtext DEFAULT NULL,
  
	PRIMARY KEY (`id`),
    FOREIGN KEY (`trainingCourse1Id`) REFERENCES `trainingCourse` (`id`)  ON DELETE CASCADE,
    FOREIGN KEY (`trainingCourse2Id`) REFERENCES `trainingCourse` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE OR REPLACE TABLE `stepType` (
    `id` bigint unsigned AUTO_INCREMENT,
    `name` VARCHAR(200) NOT NULL,
    `description` LONGTEXT,
    PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE OR REPLACE TABLE `step` (
  `id` BIGINT UNSIGNED AUTO_INCREMENT,
  `interestedId` BIGINT UNSIGNED NOT NULL,
  `stepTypeId` BIGINT UNSIGNED NOT NULL,
  `comment` LONGTEXT,
  `due` DATE,
  `created` timestamp NULL DEFAULT NULL,
  FOREIGN KEY(`interestedId`) REFERENCES `interested`(`id`) ON DELETE CASCADE,
  FOREIGN KEY(`stepTypeId`) REFERENCES `stepType`(`id`) ON DELETE CASCADE,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB;

CREATE OR REPLACE TABLE `trainee` (
  `id` bigint(20) UNSIGNED NOT NULL,
  `gender` char(1) NOT NULL,
  `firstName` varchar(200) NOT NULL,
  `surname` varchar(200) NOT NULL,
  `birthDate` date DEFAULT NULL,
  `birthLocation` varchar(200) DEFAULT NULL,
  `maritalStatus` varchar(100) DEFAULT NULL,
  `hasChilds` tinyint(1) NOT NULL DEFAULT 0,
  `street` varchar(500) DEFAULT NULL,
  `postCode` char(5) DEFAULT NULL,
  `location` varchar(500) DEFAULT NULL,
  `nationality` varchar(100) DEFAULT NULL,
  `phonePrivate` varchar(100) DEFAULT NULL,
  `phoneMobile` varchar(100) DEFAULT NULL,
  `email` varchar(200) DEFAULT NULL,
  `legalRepresentative` varchar(400) DEFAULT NULL,
  `emailLegalRepresentative` varchar(200) DEFAULT NULL,
  `phoneLegalRepresentative` varchar(100) DEFAULT NULL,
  `lastGraduation` varchar(200) DEFAULT NULL,
  `graduationYear` int(11) DEFAULT NULL,
  `lastSchool` varchar(200) DEFAULT NULL,
  `schoolFrom` date DEFAULT NULL,
  `schoolTo` date DEFAULT NULL,
  `hasBoardingSchoolExperience` tinyint(1) NOT NULL DEFAULT 0,
  `germanLevel` varchar(2) NOT NULL,
  `degreeOfVisualImpairment` char(1) DEFAULT NULL,
  `otherDisability` char(1) DEFAULT NULL,
  `requiredAccessibilityTools` longtext DEFAULT NULL,
  `handicappedIdAvailable` tinyint(1) NOT NULL DEFAULT 0,
  `medicalRemarks` longtext DEFAULT NULL,
  `pensionInsuranceNumber` char(12) DEFAULT NULL,
  `taxID` char(11) DEFAULT NULL,
  `taxClass` char(2) DEFAULT NULL,
  `denomination` varchar(50) DEFAULT NULL,
  `healthInsuranceName` varchar(200) DEFAULT NULL,
  `healthInsuranceNumber` varchar(30) DEFAULT NULL,
  `membershipCertificateForHealthInsuranceAvailable` tinyint(1) NOT NULL DEFAULT 0,
  `paymentOfSVContributions` varchar(50) DEFAULT NULL,
  `retraining` tinyint(1) NOT NULL DEFAULT 0,
  `trainingCourse1Id` bigint(20) UNSIGNED DEFAULT NULL,
  `trainingCourse2Id` bigint(20) UNSIGNED DEFAULT NULL,
  `electives` longtext DEFAULT NULL,
  `orientationWeekInterest` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekFrom` date DEFAULT NULL,
  `orientationWeekTo` date DEFAULT NULL,
  `orientationWeekAccommodationRequired` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekCostCommitmentRequested` tinyint(1) NOT NULL DEFAULT 0,
  `orientationWeekPayer` varchar(200) DEFAULT NULL,
  `orientationWeekRemarks` longtext DEFAULT NULL,
  `orientationWeekCostCommitmentReceived` tinyint(1) NOT NULL DEFAULT 0,
  `trainingFrom` date DEFAULT NULL,
  `trainingTo` date DEFAULT NULL,
  `payerName` varchar(200) DEFAULT NULL,
  `payerAddress` varchar(500) DEFAULT NULL,
  `payerContactPerson` varchar(200) DEFAULT NULL,
  `payerPhone` varchar(100) DEFAULT NULL,
  `payerCustomerNumber` varchar(100) DEFAULT NULL,
  `payerCostCommitment` varchar(20) DEFAULT NULL,
  `payerRemarks` longtext DEFAULT NULL,
  `accommodation` varchar(20) DEFAULT NULL,
  `youthProtectionExaminationReceived` tinyint(1) NOT NULL DEFAULT 0,
  `created` timestamp NOT NULL DEFAULT current_timestamp(),
  `trainingContract` varchar(20) DEFAULT NULL,
  `lpf` longtext DEFAULT NULL,
  `oAndM` longtext DEFAULT NULL,
  `trainingStartRemarks` longtext DEFAULT NULL,
  `remarksInt` longtext DEFAULT NULL,
  `sourceOfFirstContact` longtext DEFAULT NULL,
  
	PRIMARY KEY (`id`),
    FOREIGN KEY (`trainingCourse1Id`) REFERENCES `trainingCourse` (`id`)  ON DELETE CASCADE,
    FOREIGN KEY (`trainingCourse2Id`) REFERENCES `trainingCourse` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;